sudo: required

language: ruby

services:  
    - docker

env:  
  - TEST_WITH_RUBY=2.0
  - TEST_WITH_RUBY=2.1
  - TEST_WITH_RUBY=2.2
  - TEST_WITH_RUBY=2.3

before_install:
  - mv Dockerfile Dockerfile.tmp && cat Dockerfile.tmp | ruby -e "puts STDIN.read.sub(/(FROM tawan\/what-happened-base:ruby-)(.+)$/, '\1' + ENV['TEST_WITH_RUBY'])" > Dockerfile && rm Dockerfile.tmp
  - docker build -t tawan/what-happened:latest .
  - cat Dockerfile.rails-4-app | ruby -e "puts STDIN.read.sub(/(FROM tawan\/what-happened-base:ruby-)(.+)$/, '\1' + ENV['TEST_WITH_RUBY'])" > Dockerfile
  - docker build -t tawan/what-happened:rails-4-app .

install: true

script:
    - ./run_tests.rb
