sudo: required

language: ruby

services:  
    - docker

before_install:
  - mv Dockerfile Dockerfile.tmp && cat Dockerfile.tmp | ruby -e "puts STDIN.read.sub(/FROM ruby:(.+)$/, \"FROM ruby:#{ENV['TEST_WITH_RUBY']}\")" > Dockerfile && rm Dockerfile.tmp
  - docker build -t tawan/what-happened .

install: true

script:
    - docker run  tawan/what-happened bundle exec rspec spec
env:  
  global:
    - TEST_WITH_RUBY: 2.3
